# This is the Wireless Redstone main configuration file.

#        !Configuration explained!
# ConfigVersion            Do NOT change this value.
# Language                 Corresponds to the language used by the plugin.
# ColourfulLogging         Set this value to true if you want the log in the console to be written with colors (it's easier to see what's wrong).
# CheckForUpdates          If you don't want to be spammed with a message telling you that an amazing new release with new great functionalities has been released, then set it to false.
# Metrics                  Enable matrics.
# cancelChunkUnloads       Recommended to keep this value on true.
# cancelChunkUnloadRange   Correspond to the radius where the chunk won't be unloaded around the wireless sign.
# UseVault                 You have Vault but for any reason, you don't want to use it? Set this value to false.
# SilentMode               The plugin doesn't send any feedback if you don't have permissions to a certain command.
# DebugMode                Don't activate it if you're not a tester or a developer.
# DropSignWhenBroken       This value can be set to false because some people can create signs with a command and destroy them to get free signs.
# InteractTransmitterTime  The time in milliseconds you activate a transmitter if you interact with it.
# CacheRefreshFrequency    Cache refresh time in seconds, it's recommended to leave this value as it is. Max value is 480 and min value is 60.
# gateLogic                The logic of the transmitters (more info can be found on the Minecraft redstone circuit wiki), available options: OR, IGNORE (IGNORE = logic from version <2.0).
# saveOption               Save the channels in YML or SQLITE. MYSQL isn't supported yet.
# MYSQL..                  Options for MySQL, you can ignore it if you don't use it.

ConfigVersion: 2
Language: en
ColourfulLogging: true
CheckForUpdates: true
Metrics: true
cancelChunkUnloads: true
cancelChunkUnloadRange: 4
UseVault: true
SilentMode: false
DebugMode: false
DropSignWhenBroken: true
InteractTransmitterTime: 1000
CacheRefreshFrequency: 150
gateLogic: OR
saveOption: SQLITE
MySQL:
  host: 'localhost'
  port: 3306
  database: 'WirelessRedstone'
  username: 'root'
  password: ''